### ISSUE TITLE
Update python_requires to >=3.6

### ISSUE THREAD

**Issue by momikey** [nickjj/flask-static-digest#11]
First off, thank you for this extension. It seems almost perfect for the project I'm working on.

Unfortunately, I need to support Python 3.5 at a minimum for the time being, and Flask-Static-Digest fails to start due to the use of formatted string literals in `digester.py`, as these were introduced in 3.6. Everything else works without any problem I can see.

I can maintain a private fork until the systems I support are upgraded, but I would ask you to update your `python_requires` so no one else is affected.

**Comment by nickjj** [comment]
Thanks for the heads up, I just pushed the change to master. It's been so long since I started using f strings that I forgot it was only introduced in Python 3.6 (December 2016).

By the way, if you're tracking Flask master, Python 3.5 is planned to be dropped in Flask 2.0. No idea on the release date, but it's in the [their changelog](https://github.com/pallets/flask/blob/master/CHANGES.rst#version-200).
