### ISSUE TITLE
Option allows to minify static files

### ISSUE THREAD

**Issue by huynq2007** [nickjj/flask-static-digest#19]
Is it possible to add an option that allows minifying output files CSS/JS (by removing whitespace)?

**Comment by nickjj** [comment]
Hi,

Doing that would then fall into the realm of competing with tools like Webpack, Grunt or Gulp.

Those asset build tools do things like bundling up multiple files into 1 file, minify your code and remove whitespace. Bundling and properly minifying is a huge undertaking, that's why tools like Webpack exist so I recommend using that if you want an all purpose bundling and minify toolset.

If you want to blindly remove whitespace you could do something like `sed -i 's/\s+//g' $ASSET_FILE_NAME`. That'll remove any whitespace from a file. Then you could combine that with the `find` utility to do it for every CSS / JS file, drop this into a script and run that before you call `flask digest compile`.
