### ISSUE TITLE
Proposed Enhancements

### ISSUE THREAD

**Issue by jamescurtin** [nickjj/flask-static-digest#5]
Hi, @nickjj:

Wondering if you might be able to take a look at https://github.com/cookiecutter-flask/cookiecutter-flask/issues/630. The user who submitted has a few issues that are specific to how he uses Webpack, but I think there are a few broader ideas in there for potential enhancements to `flask-static-digest`.

In particular:

* Ability to serve the tagged & gzipped files separately from the main flask app
* Ability to auto-reload `cache_manifest.json` (I haven't validated, but it sounds like the app may need to be restarted after running `flask digest compile` for the changes to be discovered)

What are your thoughts?

**Comment by nickjj** [comment]
Hi,

The first issue is already a solved problem. All this extension does is take static files in -> md5 tag / gzip them and produce new static files. You can serve those files with Flask's web server, the webpack dev server, nginx or anything else you want.

Your second issue is IMO no longer something that you have to think about. It is true that the web server needs to be restart after generating static files with `flask digest compile` but you shouldn't be running that compile command on a regular basis.

It's meant to be something you run once as part of your deploy process. In development if you use the `static_url_for` template helper as a replacement for `url_for` it is smart enough to skip doing the md5 look ups if the `cache_manifest.json` file doesn't exist. So things will work seamlessly in development without compiling regularly.

**Comment by psdon** [comment]
Hi,

Yes, hashing and gziping works seemlessly. You can do this compile time in development mode (this is the problem), move the static generated file to some CDN, and then remain the manifest.json file in the Flask server. The problem is that, this build process is not viable for kind of a blog site. Which the content writers is constantly adding new images to the server (they are also allowed to upload other files.) And we cannot host that inside the Flask server, and cannot be md5 hash(md5 hashing is not a big problem though). Calling `static_url_for` will not work because the static file is not included in the `cache_manifest.json` nor within the Flask server. I know there's a hacky way to do this, but not an optimal solution. Also, reloading the `cache_manifest` without restarting the server is a good feature specially for a website that takes about 10 mins to fully boot-up.

**Comment by nickjj** [comment]
I've used this method on a bunch of sites and it works out, including sites using a CDN and with a CI pipeline.

If you have a site where people can upload images and even CSS, JS, how would your proposed solution help? Are you running the webpack dev server in production to serve your assets? Normally you would build and bundle your assets running a "production" webpack command, which would be comparable to having to run something like `flask digest compile`.

**Comment by psdon** [comment]
Yeah, I spawn a process that runs webpack production command in timely basis. I do reload the manifest file by calling the reload function:
```
@bp.route("/reload-manifest")
def reload_manifest():
    manage_webpack.reload_manifest()
    return redirect('/')
```

**Comment by nickjj** [comment]
Do you hit that endpoint every time a user uploads a file, or do you run it on a scheduled job in X intervals? Just asking because if it's interval based then what happens if a user uploads a file right now but it takes X minutes or hours to read the new manifest? Are you re-bundling all of your assets with Webpack also? That seems like it would be a time consuming process.

The building of the files is included in the docs. It's a part of my Dockerfile that gets run but it could be run on your server after git pushing your code, it's up to you. Ultimately those files then get served by nginx,

As for the CDN I can't share exact code for that since it's contract based work, but it would be copying the files from your server to whatever CDN you use if your CDN supports pushes. Alternatively you can keep serving your assets with nginx and configure your CDN to be pull based and then it will pick up and serve those files up automatically after the first request. There's not much you have to do here beyond initially configuring your CDN.

**Comment by nickjj** [comment]
With that said, user uploads is a bit more tricky. I would like to think about it more but if I were to implement this personally my first thought would be:

- User uploads the file
- Flask app md5 tags and gzips the file
- Flask app merges that new file into the existing `cache_manifest.json` file
- Flask app reloads the `cache_manifest.json` file

The last 3 steps could technically be rolled into a single function like `flask_static_digest.update_manifest('uploads/images/avatars/some-avatar-123.jpg')` and then this gets called in your file upload function.

Another option could be to call `url_for` directly if the file look up fails in the `cache_manifest.json`, and this translates to user uploads not being md5 tagged or gzipped in the end.

**Comment by psdon** [comment]
Sorry for the confusion but here's the work flow of mine to be specific. I was generalizing my inputs lately.
1. User uploaded a file. 
2. Append the unprocess file url to manifest list. I know the absolute path url of the uploaded file. I haven't publish this function yet in the repo.
3. Insert the uploaded file to assets folder. This is the remote server.
4. The file name get appended to a list of unprocess files.
5. When a threshold reached or there's no other background job, the background job get executed to compile those unprocess files from the list.
6. Upload the compiled assets to CDN.
7. Write the CDN assets url to compiled.json
8. Call an endpoint that reads the compiled.json, which also update the manifest list in the Flask server.


In this case, the whole build process is within a different server which is ideal for a big site. Just like what I said, this is not what this Flask extension is trying to solve.

**Comment by nickjj** [comment]
That seems like a very unusual work flow and truthfully I'm not sure if this library will be able to meet your requirements.

**Comment by nickjj** [comment]
Ok, I thought about this a little bit and got feedback from certain people.

Here's what I think is pretty reasonable, let me know what you think.

For user uploaded content you wouldn't ever write these entries to the manifest JSON file. Instead, you would typically upload your files to disk, S3 or somewhere else and then save the file name of the file you uploaded in your local database.

So now when you reference a user uploaded file (let's say an avatar), you would loop over your users from the database and reference the file name from the DB.

There's no need for this file to ever be in your manifest JSON. The manifest would be reserved for only static files that are a part of your repo and you can do this during your deploy process on any server (your local dev box, a CI server, directly on your production server, etc.) and it would all be the same.

But you could still md5 tag and gzip your user uploaded content at runtime at the point before you place the uploaded file into your destination (local file system or S3, etc.). This is completely separate and unrelated to this extension but I'm not 100% opposed to exposing helper functions to do the md5ing and gzipping since all of this is kind of closely related.

There's actually no need for a manifest file to store the user uploaded files because the database has a reference to the real name and then you are dynamically referencing that in your template helper, so it's never a hard coded thing that changes at the template level.

So with that said, the work flow would be like this:

- User uploads file
- You md5 tag / gzip the file (can be done now as is on your own, or maybe with helper functions later)
- You save the md5 tagged file name in your database
- You send the md5 tagged and gzipped files to its destination (local file system, S3, etc.)

**Comment by psdon** [comment]
Wow! Thanks for giving this a thorough thought process. Kudos to you Nick!

This is actually a good solution! Saving the hashed filename to database, and on the fly md5 and compression. But our case is kinda special. To speed up things, I never touch the database server. I know this can be cached in caching server so it will rarely touch the database again, but we have much more important things to be save in DB than this massive list of URLs. Plus this saves a lot bandwidth, btw.

Also the manifest doesn't need to be save in the disk in every mappings update. Uploaded file URLs only get added to Dictionary, and saved to memory. 3 million URL assets loaded in the memory only takes about 300mb, though I'm looking for more efficient solution. I've heard using 2 arrays of int for holding the keys and value can hold 30million records that only costs 50mb of RAM. Though I haven't confirmed yet.

Hashing and gzipping is not the only problem. JS and CSS files should be optimized and minified by using Webpack before saving to CDN. 

This problem already been solved using the Flask-Manage-Webpack extension. I just haven't been uploaded the new version of the extension to pypi, probably after 2 weeks from the date today when I get some time.

**Comment by nickjj** [comment]
It sounds like we'll part ways then and you can use your extension to fit your unique work flow that works for your site.

For most folks using Webpack to bundle and minify your assets is something you do at build / compile time. It's not something that runs continuously at runtime.

Also in most web apps saving a reference to a user uploaded file name is something that should really be persisted to a database. It's essential data to make your app work (like loading a user's avatar or a blog post image).

Caching it is always something you can do to minimize database calls but realistically if you're loading a blog post from the database then you already have a reference to any image's file name without an extra database call.

**Comment by psdon** [comment]
Yeah, that's right. 

This issue is good to be close I think. I just suggested to use Flask-Manage-Webpack extension instead of flask-static-digest for the cookiecutter template I used. BTW, that cookiecutter template uses Webpack and using Webpack Dev server is much faster as it doesn't need to be save in the disk in every asset changes. Than saving it to static folder and loading the asset again and again. Recompiling is inevitable for SASS users.

**Comment by nickjj** [comment]
I can't speak for the cookie cutter template author but if it were me, I would make the generator include a solution that works for a majority of people, not just 1 site.

Also Webpack's dev server isn't going to run in memory when it's being used in combination with Docker and the cookie cutter template uses Docker. You would still need to mount your static files into the container in development and even using a `tmpfs` mount makes no difference in speed due to how Docker works.

**Comment by psdon** [comment]
Make sense. I don't used Docker though. This should be good to be close. Thanks for your time and  a well thorough discussion Nick!
